export default {

  //COMBINE LOGIN AND SIGNUP ACTION
  LOGIN_USER_ACTION: 'LOGIN_USER_ACTION',
  LOGIN_USER_VALIDATE_DATA: "LOGIN_USER_VALIDATE_DATA",
  LOGIN_USER_RESPONSE: 'LOGIN_USER_RESPONSE',
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

  SIGNUP_USER_ACTION: 'SIGNUP_USER_ACTION'

};
